jobs:
  include:
    - os: linux
      dist: rhel8
      language: go
      arch: amd64
      script:
        - go run hello_world.go
    - os: RHEL
      dist: rhel8
      language: python
      arch: amd64
      script:
        - python hello_world.py
    - os: rhel
      dist: rhel8
      language: java
      arch: amd64
      script:
        - javac hello_world.java
        - java HelloWorld
